### PR TITLE
Add welcome screen

### PR DESCRIPTION
**Pull request by danshuri**
Hello there,

Simple welcome screen when you run the app, with a title, message and button to start the game.
When the loading is done, the 'start' button appears.

### CODE REVIEW

**Comment by swift502** [comment]
Wow, somebody made a pull request 😄

Thanks a lot, a welcome screen was on my TODO list.
I thought of getting back to this project. Might do some work soon. This definitely motivates me to finish a demo I had in mind with few simple scenarios, AI racing, spawn points and three.js tonemapping and make it public.

Again thanks, I'll check it out when I get home and let you know if it's fine.

**Comment by danshuri** [comment]
Hello Jan,

I've looked at your TODO list yesterday, to check where I could help.
Let me know if you were expecting something different. I did a few other things like a logo but I thought it would be better to do it minimal and viable.

I've seen your demo on the Three.js forum when it was just your boxman running around with awesome physics. I am amazed to see how incredibly rich it is now, and I'm glad that it motivates you to getting back on it 🙂

**Comment by swift502** [comment]
I think it's a perfect start. I might tweak the visuals a bit later if you don't mind, but for now it's perfect. 👍
I'll try to do some other stuff from the TODO list first, I'll see how far I can get before losing motivation once again.

**Comment by danshuri** [comment]
Cool. the audio experiment stuff is no more interesting? Too bad! ^^

**Comment by swift502** [comment]
😃  Not "no more interesting", just has less priority. I'll have to cut some stuff out of this new demo if I ever want to get it out...
I moved it into the 0.X Project, under "research". I wanted to look into dynamic engine sound synthesis, add footsteps and such, but that's a whole chapter I haven't even begun looking into.

**Pull request merged**
